"""increase hospital phone length

Revision ID: 867dff8f0a93
Revises: 02cc2b7c037b
Create Date: 2025-01-03 21:11:42.224556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '867dff8f0a93'
down_revision: Union[str, None] = '02cc2b7c037b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospitals', 'hospital_phone',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hospitals', 'hospital_phone',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###
