"""Create HealthReport table and relationships

Revision ID: c2ead0f9aa1e
Revises: fa4ed368167d
Create Date: 2025-01-18 21:15:08.328379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2ead0f9aa1e'
down_revision: Union[str, None] = 'fa4ed368167d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor_reminders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_reminders',
    sa.Column('reminder_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reminder_content', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('reminder_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.appointment_id'], name='doctor_reminders_appointment_id_fkey'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.doctor_id'], name='doctor_reminders_doctor_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], name='doctor_reminders_patient_id_fkey'),
    sa.PrimaryKeyConstraint('reminder_id', name='doctor_reminders_pkey')
    )
    # ### end Alembic commands ###
